services:
  bq-postgres:
    image: postgres:15.3-alpine
    container_name: asisto-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: asisto
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: local-network
    external: true
